
import { LogEntry } from './types';

export const MOCK_LOGS: LogEntry[] = [
  {
    id: '1',
    index: 1,
    userName: '孙兆正',
    userAccount: 'suncz',
    department: '华夏财富',
    content: '帮我根据图中的数据制作一个柱状图',
    source: 'pc',
    isOnline: 0,
    isKnowledgeBase: 0,
    isFileQA: 1,
    intentType: '绘图',
    thinkingProcess: '首先，用户的问题是：“帮我根据...”',
    answerContent: '根据您提供的文件内容，我无法直接生成图片...',
    chatId: '430865',
    questionId: '430867',
    answerId: '430869',
    userType: 'normal'
  },
  {
    id: '2',
    index: 2,
    userName: '孙嘉辉',
    userAccount: 'sunjiahui',
    department: '金融科技部',
    content: 'public class ProductBaseElementDetailDT...',
    source: 'pc',
    isOnline: 0,
    isKnowledgeBase: 0,
    isFileQA: 1,
    intentType: '代码解释',
    thinkingProcess: '',
    answerContent: '以下是根据您提供的 ProductBa...',
    chatId: '430708',
    questionId: '430762',
    answerId: '430764',
    userType: 'normal'
  },
  {
    id: '3',
    index: 3,
    userName: '孙嘉辉',
    userAccount: 'sunjiahui',
    department: '金融科技部',
    content: '我更需要注册哈，中文内容，然后第一列...',
    source: 'pc',
    isOnline: 0,
    isKnowledgeBase: 0,
    isFileQA: 1,
    intentType: '格式化',
    thinkingProcess: '首先，用户的需求是输出一份Ex...',
    answerContent: '以下是根据您提供的内容...',
    chatId: '430708',
    questionId: '430735',
    answerId: '430737',
    userType: 'normal'
  },
  {
    id: '4',
    index: 4,
    userName: '孙嘉辉',
    userAccount: 'sunjiahui',
    department: '金融科技部',
    content: '今天是几号',
    source: 'cbl',
    isOnline: 0,
    isKnowledgeBase: 0,
    isFileQA: 0,
    intentType: '模型回答',
    thinkingProcess: '',
    answerContent: '今天是2024年6月21日，星期五。',
    chatId: '430745',
    questionId: '430747',
    answerId: '430749',
    userType: 'normal'
  },
  {
    id: '5',
    index: 5,
    userName: '李彩云',
    userAccount: 'licy',
    department: '基金营销部',
    content: '洗衣店来公司洗衣时间',
    source: 'sszx',
    isOnline: 0,
    isKnowledgeBase: 1,
    isFileQA: 0,
    intentType: '知识问答',
    thinkingProcess: '',
    answerContent: '**北辰办公区洗衣服务时间汇总**...',
    chatId: '430681',
    questionId: '430682',
    answerId: '430684',
    userType: 'normal'
  },
  {
    id: '6',
    index: 6,
    userName: '张小凡',
    userAccount: 'zhangxf',
    department: '投资管理部',
    content: '分析一下最近一周的科技股走势',
    source: 'pc',
    isOnline: 1,
    isKnowledgeBase: 0,
    isFileQA: 0,
    isDeepThinking: 1,
    intentType: '市场分析',
    thinkingProcess: '正在联网搜索科技股动态...',
    answerContent: '科技股本周表现强劲，特别是AI板块...',
    chatId: '430880',
    questionId: '430881',
    answerId: '430882',
    userType: 'normal'
  },
  {
    id: '7',
    index: 7,
    userName: '王建国',
    userAccount: 'wangjg',
    department: '风险控制部',
    content: '如何配置风控系统的预警阈值',
    source: 'pc',
    isOnline: 0,
    isKnowledgeBase: 1,
    isFileQA: 1,
    intentType: '业务咨询',
    thinkingProcess: '检索风控知识库手册...',
    answerContent: '预警阈值的配置需要根据资产类别设定...',
    chatId: '430900',
    questionId: '430901',
    answerId: '430902',
    userType: 'normal'
  },
  {
    id: '8',
    index: 8,
    userName: '赵敏',
    userAccount: 'zhaom',
    department: '人力资源部',
    content: '生成一份关于员工培训的PPT大纲',
    source: 'mobile',
    isOnline: 0,
    isKnowledgeBase: 0,
    isFileQA: 0,
    intentType: '文案创作',
    thinkingProcess: '',
    answerContent: '以下是为您准备的培训大纲：1. 培训目标...',
    chatId: '430910',
    questionId: '430911',
    answerId: '430912',
    userType: 'normal'
  },
  {
    id: '9',
    index: 9,
    userName: '刘伟',
    userAccount: 'liuw',
    department: '运营保障部',
    content: '查询明天的天气预报',
    source: 'pc',
    isOnline: 1,
    isKnowledgeBase: 0,
    isFileQA: 0,
    intentType: '生活查询',
    thinkingProcess: '调用天气API...',
    answerContent: '明天晴转多云，气温22-28度。',
    chatId: '430920',
    questionId: '430921',
    answerId: '430922',
    userType: 'normal'
  },
  {
    id: '10',
    index: 10,
    userName: '陈婷',
    userAccount: 'chent',
    department: '合规部',
    content: '解释一下新的证券法修正案',
    source: 'pc',
    isOnline: 1,
    isKnowledgeBase: 1,
    isFileQA: 0,
    isDeepThinking: 1,
    intentType: '法律解读',
    thinkingProcess: '深度理解修正案条文并结合现有法规...',
    answerContent: '新的证券法修正案主要在投资者保护方面...',
    chatId: '430930',
    questionId: '430931',
    answerId: '430932',
    userType: 'normal'
  }
];
